# Group Affective Behavior (GAB) and Hostile Affect Development (E.26)

In [1]:
# GAB --> balance of positive and negative sentiment in conversation
# subtract negativity from positivity (discard neutrality)

# get all positive_bert and negative_bert scores for a given conversation from chat level ouput

import pandas as pd

df = pd.read_csv('../output/csopII_output_chat_level.csv', encoding='mac_roman')
df

FileNotFoundError: [Errno 2] No such file or directory: '../output/csopII_output_chat_level.csv'

In [4]:
def group_affective_behavior(chat_df):

    # gab = chat_df[['conversation_num']].drop_duplicates()
    gab = []

    for conv in chat_df.groupby(['conversation_num']):
        # print(conv[1]['positive_bert'])

        gab.append(conv[1]['positive_bert'].sum() - conv[1]['negative_bert'].sum())
    
    return pd.DataFrame({'gab':gab})

group_affective_behavior(df)

          gab
0    1.310083
1    0.131912
2    0.131912
3    0.131912
4    0.131912
..        ...
957 -0.445389
958  0.131912
959  0.131912
960 -1.060671
961  0.131912

[962 rows x 1 columns]

In [3]:
# Hostile Affect --> number of occurrences of "hostile" behavior
# Contempt (" belittle, hurt, or humiliate"), criticism ("highlight [...] as inherently defective"), stonewalling ("communicate an unwillingness to listen or respond"), defensiveness ("deflect responsibility or blame")

# Chat level feature, evaluate toxicity of each message
# Potential tools --> Perspective API, BERT toxic language classification, RECAST model

In [6]:
# Perspective API Key: AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4
# Limitation --> 1 query/second


from googleapiclient import discovery
import json

API_KEY = 'AIzaSyBvApFd8k1e0VaYO9iGmXlXUO8525Ln5X4'

client = discovery.build(
  "commentanalyzer",
  "v1alpha1",
  developerKey=API_KEY,
  discoveryServiceUrl="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
  static_discovery=False,
)

def hostile_instances(chat):
  # print(type(chat))
  if chat:
    analyze_request = {
      'comment': { 'text': chat },
      'requestedAttributes': {'TOXICITY': {}},
      'languages': ["en"]
    }

    response = client.comments().analyze(body=analyze_request).execute()
    return response['attributeScores']['TOXICITY']['summaryScore']['value']
  # print(f"toxicity: {response['attributeScores']['TOXICITY']['summaryScore']['value']}")

In [2]:
import re

def preprocess_conversation_columns(df):
	# remove all special characters from df
	df.columns = df.columns.str.replace('[^A-Za-z0-9_]', '', regex=True)
	
	# If data is grouped by batch/round, add a conversation num
	if {'batch_num', 'round_num'}.issubset(df.columns):
		df['conversation_num'] = df.groupby(['batch_num', 'round_num']).ngroup()
		df = df[df.columns.tolist()[-1:] + df.columns.tolist()[0:-1]] # make the new column first

	return(df)

def preprocess_text(text):
  	# For each individual message: preprocess to remove anything that is not an alphabet or number from the string
	return(re.sub(r"[^a-zA-Z0-9 ]+", '',text).lower())

In [4]:
import pandas as pd
df = pd.read_csv('./data/raw_data/juries_tiny_for_testing.csv', encoding='mac_roman')
df = preprocess_conversation_columns(df)
df["message"] = df["message"].astype(str).apply(preprocess_text)
df

,conversation_num,batch_num,round_num,speaker_hash,speaker_nickname,timestamp,message,majority_pct,num_flipped,flipped_pct,num_votes
0,0,0,0,5e7e1e0031f4e454e196c30b,niceRhino,2020-04-20T18:27:20.125Z,hello,1.0,1,0.333333,3
1,0,0,0,5e31d6e4e31c5304c46f1413,culturedCow,2020-04-20T18:27:23.764Z,hi,1.0,1,0.333333,3
2,0,0,0,5e7e4f4c31f4e454e196c9c4,spryBison,2020-04-20T18:27:27.724Z,hello,1.0,1,0.333333,3
3,0,0,0,5d482ea421c9be351f762255,youngLion,2020-04-20T18:27:30.410Z,hi,1.0,1,0.333333,3
4,0,0,0,5e84cc3c50f6e364321d6265,smallGiraffe,2020-04-20T18:27:35.506Z,hi,1.0,1,0.333333,3
...,...,...,...,...,...,...,...,...,...,...,...
92,1,0,2,5e7e4f4c31f4e454e196c9c4,newLion,2020-04-20T19:02:55.111Z,i say asshole under stress,0.6,0,0.000000,5
93,1,0,2,5d6feec65f80ae21f5c5f054,conventionalMonkey,2020-04-20T19:03:21.819Z,yes she is the asshole unfortunately husband h...,0.6,0,0.000000,5
94,1,0,2,5d482ea421c9be351f762255,newPanda,2020-04-20T19:03:36.308Z,i think she is being presumptuous and acting l...,0.6,0,0.000000,5
95,1,0,2,5e7e4f4c31f4e454e196c9c4,newLion,2020-04-20T19:03:53.219Z,thas true she inst considering her husband and...,0.6,0,0.000000,5
96,1,0,2,5e84cc3c50f6e364321d6265,likelyRabbit,2020-04-20T19:04:02.642Z,i dont agree not the asshole shes too busy,0.6,0,0.000000,5

In [7]:
df['toxicity'] = df['message'].apply(hostile_instances)
df
# df['toxicity']
# df['message'].apply(hostile_instances)

,conversation_num,batch_num,round_num,speaker_hash,speaker_nickname,timestamp,message,majority_pct,num_flipped,flipped_pct,num_votes,toxicity
0,0,0,0,5e7e1e0031f4e454e196c30b,niceRhino,2020-04-20T18:27:20.125Z,hello,1.0,1,0.333333,3,0.016022
1,0,0,0,5e31d6e4e31c5304c46f1413,culturedCow,2020-04-20T18:27:23.764Z,hi,1.0,1,0.333333,3,0.017216
2,0,0,0,5e7e4f4c31f4e454e196c9c4,spryBison,2020-04-20T18:27:27.724Z,hello,1.0,1,0.333333,3,0.019477
3,0,0,0,5d482ea421c9be351f762255,youngLion,2020-04-20T18:27:30.410Z,hi,1.0,1,0.333333,3,0.017216
4,0,0,0,5e84cc3c50f6e364321d6265,smallGiraffe,2020-04-20T18:27:35.506Z,hi,1.0,1,0.333333,3,0.017216
...,...,...,...,...,...,...,...,...,...,...,...,...
92,1,0,2,5e7e4f4c31f4e454e196c9c4,newLion,2020-04-20T19:02:55.111Z,i say asshole under stress,0.6,0,0.000000,5,0.833343
93,1,0,2,5d6feec65f80ae21f5c5f054,conventionalMonkey,2020-04-20T19:03:21.819Z,yes she is the asshole unfortunately husband h...,0.6,0,0.000000,5,0.858507
94,1,0,2,5d482ea421c9be351f762255,newPanda,2020-04-20T19:03:36.308Z,i think she is being presumptuous and acting l...,0.6,0,0.000000,5,0.200795
95,1,0,2,5e7e4f4c31f4e454e196c9c4,newLion,2020-04-20T19:03:53.219Z,thas true she inst considering her husband and...,0.6,0,0.000000,5,0.057501
96,1,0,2,5e84cc3c50f6e364321d6265,likelyRabbit,2020-04-20T19:04:02.642Z,i dont agree not the asshole shes too busy,0.6,0,0.000000,5,0.736634

In [27]:
# BERT Language classification - time expense!

from detoxify import Detoxify
results = Detoxify('original').predict('example text')
print(results)

Downloading: "https://github.com/unitaryai/detoxify/releases/download/v0.1-alpha/toxic_original-c1212f89.ckpt" to /Users/agshruti/.cache/torch/hub/checkpoints/toxic_original-c1212f89.ckpt
100%|██████████| 418M/418M [01:02<00:00, 6.98MB/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]